
#开发配置
server:
  port: 8070
spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/villagequestion?useUnicode=true&amp;characterEncoding=UTF-8&amp;serverTimezone=UTC&amp;verifyServerCertificate=false&amp;useSSL=false&amp;allowMultiQueries=true
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  application:
    name:smallTadpole
swagger: ##给swagger设置一个开关
  ebable: true
wx:
  miniapp:
    configs:
        - appid: wx38b57e4dc4563a12
          secret: 9c6b1f39e4c22834337edce53562572f
          token: #微信小程序消息服务器配置的token
          aesKey: #微信小程序消息服务器配置的EncodingAESKey
          msgDataFormat: JSON

    exception:
      exceptionList:
        - status: 100
          mesg: 微信登陆失败
        - status: 101
          mesg: 微信调用失败
        - status: 102
          mesg: 登陆的appid和code不能为空 /login/{appid}/{code}

pic:
  upload:
    path: D:\tmp
