package com.small.tadpole.domain;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table question
 */
@ApiModel(value="com.small.tadpole.domain.Question")
public class Question {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table question
     *
     * @mbg.generated Fri Mar 13 12:42:21 CST 2020
     */
    public static final Integer IS_DELETED = IsDel.IS_DELETED.value();

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table question
     *
     * @mbg.generated Fri Mar 13 12:42:21 CST 2020
     */
    public static final Integer NOT_DELETED = IsDel.NOT_DELETED.value();

    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.id
     *
     * @mbg.generated Fri Mar 13 12:42:21 CST 2020
     */
    @ApiModelProperty(value="idid")
    private Integer id;

    /**
     * Database Column Remarks:
     *   标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.title
     *
     * @mbg.generated Fri Mar 13 12:42:21 CST 2020
     */
    @ApiModelProperty(value="title标题")
    private String title;

    /**
     * Database Column Remarks:
     *   创建日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.create_time
     *
     * @mbg.generated Fri Mar 13 12:42:21 CST 2020
     */
    @ApiModelProperty(value="createTime创建日期")
    private LocalDateTime createTime;

    /**
     * Database Column Remarks:
     *   是否处理完成
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.is_done
     *
     * @mbg.generated Fri Mar 13 12:42:21 CST 2020
     */
    @ApiModelProperty(value="isDone是否处理完成")
    private Integer isDone;

    /**
     * Database Column Remarks:
     *   浏览次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.scan_times
     *
     * @mbg.generated Fri Mar 13 12:42:21 CST 2020
     */
    @ApiModelProperty(value="scanTimes浏览次数")
    private Integer scanTimes;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.uid
     *
     * @mbg.generated Fri Mar 13 12:42:21 CST 2020
     */
    @ApiModelProperty(value="uid用户id")
    private Integer uid;

    /**
     * Database Column Remarks:
     *   是否删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.is_del
     *
     * @mbg.generated Fri Mar 13 12:42:21 CST 2020
     */
    @ApiModelProperty(value="isDel是否删除")
    private Integer isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.id
     *
     * @return the value of question.id
     *
     * @mbg.generated Fri Mar 13 12:42:21 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.id
     *
     * @param id the value for question.id
     *
     * @mbg.generated Fri Mar 13 12:42:21 CST 2020
     */
    public Question setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.title
     *
     * @return the value of question.title
     *
     * @mbg.generated Fri Mar 13 12:42:21 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.title
     *
     * @param title the value for question.title
     *
     * @mbg.generated Fri Mar 13 12:42:21 CST 2020
     */
    public Question setTitle(String title) {
        this.title = title;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.create_time
     *
     * @return the value of question.create_time
     *
     * @mbg.generated Fri Mar 13 12:42:21 CST 2020
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.create_time
     *
     * @param createTime the value for question.create_time
     *
     * @mbg.generated Fri Mar 13 12:42:21 CST 2020
     */
    public Question setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.is_done
     *
     * @return the value of question.is_done
     *
     * @mbg.generated Fri Mar 13 12:42:21 CST 2020
     */
    public Integer getIsDone() {
        return isDone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.is_done
     *
     * @param isDone the value for question.is_done
     *
     * @mbg.generated Fri Mar 13 12:42:21 CST 2020
     */
    public Question setIsDone(Integer isDone) {
        this.isDone = isDone;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.scan_times
     *
     * @return the value of question.scan_times
     *
     * @mbg.generated Fri Mar 13 12:42:21 CST 2020
     */
    public Integer getScanTimes() {
        return scanTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.scan_times
     *
     * @param scanTimes the value for question.scan_times
     *
     * @mbg.generated Fri Mar 13 12:42:21 CST 2020
     */
    public Question setScanTimes(Integer scanTimes) {
        this.scanTimes = scanTimes;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.uid
     *
     * @return the value of question.uid
     *
     * @mbg.generated Fri Mar 13 12:42:21 CST 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.uid
     *
     * @param uid the value for question.uid
     *
     * @mbg.generated Fri Mar 13 12:42:21 CST 2020
     */
    public Question setUid(Integer uid) {
        this.uid = uid;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Fri Mar 13 12:42:21 CST 2020
     */
    public void andLogicalDeleted(boolean deleted) {
        setIsDel(deleted ? IsDel.IS_DELETED.value() : IsDel.NOT_DELETED.value());
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.is_del
     *
     * @return the value of question.is_del
     *
     * @mbg.generated Fri Mar 13 12:42:21 CST 2020
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.is_del
     *
     * @param isDel the value for question.is_del
     *
     * @mbg.generated Fri Mar 13 12:42:21 CST 2020
     */
    public Question setIsDel(Integer isDel) {
        this.isDel = isDel;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Fri Mar 13 12:42:21 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", IS_DELETED=").append(IS_DELETED);
        sb.append(", NOT_DELETED=").append(NOT_DELETED);
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", createTime=").append(createTime);
        sb.append(", isDone=").append(isDone);
        sb.append(", scanTimes=").append(scanTimes);
        sb.append(", uid=").append(uid);
        sb.append(", isDel=").append(isDel);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Fri Mar 13 12:42:21 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Question other = (Question) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getIsDone() == null ? other.getIsDone() == null : this.getIsDone().equals(other.getIsDone()))
            && (this.getScanTimes() == null ? other.getScanTimes() == null : this.getScanTimes().equals(other.getScanTimes()))
            && (this.getUid() == null ? other.getUid() == null : this.getUid().equals(other.getUid()))
            && (this.getIsDel() == null ? other.getIsDel() == null : this.getIsDel().equals(other.getIsDel()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Fri Mar 13 12:42:21 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getIsDone() == null) ? 0 : getIsDone().hashCode());
        result = prime * result + ((getScanTimes() == null) ? 0 : getScanTimes().hashCode());
        result = prime * result + ((getUid() == null) ? 0 : getUid().hashCode());
        result = prime * result + ((getIsDel() == null) ? 0 : getIsDel().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table question
     *
     * @mbg.generated Fri Mar 13 12:42:21 CST 2020
     */
    public enum IsDel {
        NOT_DELETED(new Integer("0"), "未删除"),
        IS_DELETED(new Integer("1"), "已删除");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table question
         *
         * @mbg.generated Fri Mar 13 12:42:21 CST 2020
         */
        private final Integer value;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table question
         *
         * @mbg.generated Fri Mar 13 12:42:21 CST 2020
         */
        private final String name;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table question
         *
         * @mbg.generated Fri Mar 13 12:42:21 CST 2020
         */
        IsDel(Integer value, String name) {
            this.value = value;
            this.name = name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table question
         *
         * @mbg.generated Fri Mar 13 12:42:21 CST 2020
         */
        public Integer getValue() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table question
         *
         * @mbg.generated Fri Mar 13 12:42:21 CST 2020
         */
        public Integer value() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table question
         *
         * @mbg.generated Fri Mar 13 12:42:21 CST 2020
         */
        public String getName() {
            return this.name;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table question
     *
     * @mbg.generated Fri Mar 13 12:42:21 CST 2020
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        title("title", "title", "VARCHAR", false),
        createTime("create_time", "createTime", "TIMESTAMP", false),
        isDone("is_done", "isDone", "INTEGER", false),
        scanTimes("scan_times", "scanTimes", "INTEGER", false),
        uid("uid", "uid", "INTEGER", true),
        isDel("is_del", "isDel", "INTEGER", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table question
         *
         * @mbg.generated Fri Mar 13 12:42:21 CST 2020
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table question
         *
         * @mbg.generated Fri Mar 13 12:42:21 CST 2020
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table question
         *
         * @mbg.generated Fri Mar 13 12:42:22 CST 2020
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table question
         *
         * @mbg.generated Fri Mar 13 12:42:22 CST 2020
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table question
         *
         * @mbg.generated Fri Mar 13 12:42:22 CST 2020
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table question
         *
         * @mbg.generated Fri Mar 13 12:42:22 CST 2020
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table question
         *
         * @mbg.generated Fri Mar 13 12:42:22 CST 2020
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table question
         *
         * @mbg.generated Fri Mar 13 12:42:22 CST 2020
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table question
         *
         * @mbg.generated Fri Mar 13 12:42:22 CST 2020
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table question
         *
         * @mbg.generated Fri Mar 13 12:42:22 CST 2020
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table question
         *
         * @mbg.generated Fri Mar 13 12:42:22 CST 2020
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table question
         *
         * @mbg.generated Fri Mar 13 12:42:22 CST 2020
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table question
         *
         * @mbg.generated Fri Mar 13 12:42:22 CST 2020
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table question
         *
         * @mbg.generated Fri Mar 13 12:42:22 CST 2020
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table question
         *
         * @mbg.generated Fri Mar 13 12:42:22 CST 2020
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table question
         *
         * @mbg.generated Fri Mar 13 12:42:22 CST 2020
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}