package com.small.tadpole.domain;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table question_deal_log
 */
@ApiModel(value="com.small.tadpole.domain.QuestionDealLog")
public class QuestionDealLog {
    /**
     * Database Column Remarks:
     *   处理日志ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_deal_log.deal_id
     *
     * @mbg.generated Sat Mar 14 16:08:31 CST 2020
     */
    @ApiModelProperty(value="dealId处理日志ID")
    private Integer dealId;

    /**
     * Database Column Remarks:
     *   问题ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_deal_log.id
     *
     * @mbg.generated Sat Mar 14 16:08:31 CST 2020
     */
    @ApiModelProperty(value="id问题ID")
    private Integer id;

    /**
     * Database Column Remarks:
     *   评论,描述处理情况
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_deal_log.note
     *
     * @mbg.generated Sat Mar 14 16:08:31 CST 2020
     */
    @ApiModelProperty(value="note评论,描述处理情况")
    private String note;

    /**
     * Database Column Remarks:
     *   处理状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_deal_log.state
     *
     * @mbg.generated Sat Mar 14 16:08:31 CST 2020
     */
    @ApiModelProperty(value="state处理状态")
    private Integer state;

    /**
     * Database Column Remarks:
     *   流水时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_deal_log.deal_time
     *
     * @mbg.generated Sat Mar 14 16:08:31 CST 2020
     */
    @ApiModelProperty(value="dealTime流水时间")
    private LocalDateTime dealTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_deal_log.deal_id
     *
     * @return the value of question_deal_log.deal_id
     *
     * @mbg.generated Sat Mar 14 16:08:31 CST 2020
     */
    public Integer getDealId() {
        return dealId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_deal_log.deal_id
     *
     * @param dealId the value for question_deal_log.deal_id
     *
     * @mbg.generated Sat Mar 14 16:08:31 CST 2020
     */
    public QuestionDealLog setDealId(Integer dealId) {
        this.dealId = dealId;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_deal_log.id
     *
     * @return the value of question_deal_log.id
     *
     * @mbg.generated Sat Mar 14 16:08:31 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_deal_log.id
     *
     * @param id the value for question_deal_log.id
     *
     * @mbg.generated Sat Mar 14 16:08:31 CST 2020
     */
    public QuestionDealLog setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_deal_log.note
     *
     * @return the value of question_deal_log.note
     *
     * @mbg.generated Sat Mar 14 16:08:31 CST 2020
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_deal_log.note
     *
     * @param note the value for question_deal_log.note
     *
     * @mbg.generated Sat Mar 14 16:08:31 CST 2020
     */
    public QuestionDealLog setNote(String note) {
        this.note = note;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_deal_log.state
     *
     * @return the value of question_deal_log.state
     *
     * @mbg.generated Sat Mar 14 16:08:31 CST 2020
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_deal_log.state
     *
     * @param state the value for question_deal_log.state
     *
     * @mbg.generated Sat Mar 14 16:08:31 CST 2020
     */
    public QuestionDealLog setState(Integer state) {
        this.state = state;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_deal_log.deal_time
     *
     * @return the value of question_deal_log.deal_time
     *
     * @mbg.generated Sat Mar 14 16:08:31 CST 2020
     */
    public LocalDateTime getDealTime() {
        return dealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_deal_log.deal_time
     *
     * @param dealTime the value for question_deal_log.deal_time
     *
     * @mbg.generated Sat Mar 14 16:08:31 CST 2020
     */
    public QuestionDealLog setDealTime(LocalDateTime dealTime) {
        this.dealTime = dealTime;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_deal_log
     *
     * @mbg.generated Sat Mar 14 16:08:31 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dealId=").append(dealId);
        sb.append(", id=").append(id);
        sb.append(", note=").append(note);
        sb.append(", state=").append(state);
        sb.append(", dealTime=").append(dealTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_deal_log
     *
     * @mbg.generated Sat Mar 14 16:08:31 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        QuestionDealLog other = (QuestionDealLog) that;
        return (this.getDealId() == null ? other.getDealId() == null : this.getDealId().equals(other.getDealId()))
            && (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getNote() == null ? other.getNote() == null : this.getNote().equals(other.getNote()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getDealTime() == null ? other.getDealTime() == null : this.getDealTime().equals(other.getDealTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_deal_log
     *
     * @mbg.generated Sat Mar 14 16:08:31 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDealId() == null) ? 0 : getDealId().hashCode());
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getNote() == null) ? 0 : getNote().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getDealTime() == null) ? 0 : getDealTime().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table question_deal_log
     *
     * @mbg.generated Sat Mar 14 16:08:31 CST 2020
     */
    public enum Column {
        dealId("deal_id", "dealId", "INTEGER", false),
        id("id", "id", "INTEGER", false),
        note("note", "note", "VARCHAR", false),
        state("state", "state", "INTEGER", true),
        dealTime("deal_time", "dealTime", "TIMESTAMP", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table question_deal_log
         *
         * @mbg.generated Sat Mar 14 16:08:31 CST 2020
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table question_deal_log
         *
         * @mbg.generated Sat Mar 14 16:08:31 CST 2020
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table question_deal_log
         *
         * @mbg.generated Sat Mar 14 16:08:31 CST 2020
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table question_deal_log
         *
         * @mbg.generated Sat Mar 14 16:08:31 CST 2020
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table question_deal_log
         *
         * @mbg.generated Sat Mar 14 16:08:31 CST 2020
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table question_deal_log
         *
         * @mbg.generated Sat Mar 14 16:08:31 CST 2020
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table question_deal_log
         *
         * @mbg.generated Sat Mar 14 16:08:31 CST 2020
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table question_deal_log
         *
         * @mbg.generated Sat Mar 14 16:08:31 CST 2020
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table question_deal_log
         *
         * @mbg.generated Sat Mar 14 16:08:31 CST 2020
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table question_deal_log
         *
         * @mbg.generated Sat Mar 14 16:08:31 CST 2020
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table question_deal_log
         *
         * @mbg.generated Sat Mar 14 16:08:31 CST 2020
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table question_deal_log
         *
         * @mbg.generated Sat Mar 14 16:08:31 CST 2020
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table question_deal_log
         *
         * @mbg.generated Sat Mar 14 16:08:31 CST 2020
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table question_deal_log
         *
         * @mbg.generated Sat Mar 14 16:08:31 CST 2020
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table question_deal_log
         *
         * @mbg.generated Sat Mar 14 16:08:31 CST 2020
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table question_deal_log
         *
         * @mbg.generated Sat Mar 14 16:08:31 CST 2020
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}