package com.small.tadpole.mapper;

import com.small.tadpole.domain.QuestionDetail;
import com.small.tadpole.domain.QuestionDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuestionDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_detail
     *
     * @mbg.generated Sat Mar 14 15:53:49 CST 2020
     */
    long countByExample(QuestionDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_detail
     *
     * @mbg.generated Sat Mar 14 15:53:49 CST 2020
     */
    int deleteByExample(QuestionDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_detail
     *
     * @mbg.generated Sat Mar 14 15:53:49 CST 2020
     */
    int insert(QuestionDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_detail
     *
     * @mbg.generated Sat Mar 14 15:53:49 CST 2020
     */
    int insertSelective(QuestionDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_detail
     *
     * @mbg.generated Sat Mar 14 15:53:49 CST 2020
     */
    QuestionDetail selectOneByExample(QuestionDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_detail
     *
     * @mbg.generated Sat Mar 14 15:53:49 CST 2020
     */
    QuestionDetail selectOneByExampleSelective(@Param("example") QuestionDetailExample example, @Param("selective") QuestionDetail.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_detail
     *
     * @mbg.generated Sat Mar 14 15:53:49 CST 2020
     */
    List<QuestionDetail> selectByExampleSelective(@Param("example") QuestionDetailExample example, @Param("selective") QuestionDetail.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_detail
     *
     * @mbg.generated Sat Mar 14 15:53:49 CST 2020
     */
    List<QuestionDetail> selectByExample(QuestionDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_detail
     *
     * @mbg.generated Sat Mar 14 15:53:49 CST 2020
     */
    int updateByExampleSelective(@Param("record") QuestionDetail record, @Param("example") QuestionDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_detail
     *
     * @mbg.generated Sat Mar 14 15:53:49 CST 2020
     */
    int updateByExample(@Param("record") QuestionDetail record, @Param("example") QuestionDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_detail
     *
     * @mbg.generated Sat Mar 14 15:53:49 CST 2020
     */
    int logicalDeleteByExample(@Param("example") QuestionDetailExample example);
}